spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12341234
    url: jdbc:mysql://localhost:3306/novel
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: create
logging:
  level:
    root: info
    com.brad.novel: debug